# -*- coding: utf-8 -*-
"""ml_logreg.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/16JAmHOKOTWCERk2qEetfD8sqSqfkC93x
"""

from __future__ import annotations

import itertools
import time
from typing import Any, Dict, Optional, Sequence, Tuple

import numpy as np
from scipy.sparse import hstack, csr_matrix, issparse
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import f1_score


# -------------------------------------------------------------------
# 0. Internal helper: combine text + extra features
# -------------------------------------------------------------------

def _build_augmented_matrix(X_text, X_extra):
    """
    Combine TF-IDF text features with extra numeric features.
    If X_extra is None, returns X_text as-is.
    """
    if X_extra is None:
        return X_text

    if not issparse(X_text):
        raise ValueError("X_text should be a sparse matrix (e.g., TF-IDF).")

    # Convert dense extras to sparse if needed
    if X_extra is not None and not issparse(X_extra):
        X_extra = csr_matrix(X_extra)

    return hstack([X_text, X_extra])


# -------------------------------------------------------------------
# 1. Core trainer (feature-agnostic)
# -------------------------------------------------------------------

def train_logreg(
    X_train_text,
    y_train: Sequence[int],
    X_val_text,
    y_val: Sequence[int],
    X_train_extra=None,
    X_val_extra=None,
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[LogisticRegression, Dict[str, Any], float]:
    """
    Core Logistic Regression training with manual grid search.

    - Works with:
        * text-only:   pass X_*_extra=None
        * text+extra:  pass extra arrays/matrices
    - Uses weighted F1 on the validation set to pick the best model.

    Parameters
    ----------
    X_train_text, X_val_text : sparse matrices (TF-IDF)
    X_train_extra, X_val_extra : np.ndarray or sparse matrices (or None)
    y_train, y_val : label arrays
    param_grid : dict of hyperparameters -> list of values
    random_state : for LR reproducibility
    verbose : print progress and results

    Returns
    -------
    best_model : fitted LogisticRegression
    best_params : dict of best hyperparameters
    best_f1 : best validation F1 (weighted)
    """
    if param_grid is None:
        param_grid = {
            "C": [0.1, 1, 10],
            "solver": ["lbfgs", "saga"],
            "penalty": ["l2"],
            # "multi_class": ["multinomial"],
            "class_weight": ["balanced", None],
        }

    # Combine text + extra into augmented design matrices
    X_train = _build_augmented_matrix(X_train_text, X_train_extra)
    X_val = _build_augmented_matrix(X_val_text, X_val_extra)

    y_train = np.asarray(y_train)
    y_val = np.asarray(y_val)

    # Generate all hyperparameter combinations
    keys = list(param_grid.keys())
    values = [param_grid[k] for k in keys]
    all_param_combos = [dict(zip(keys, v)) for v in itertools.product(*values)]

    best_f1 = -1.0
    best_model = None
    best_params: Dict[str, Any] = {}

    if verbose:
        print(f"\n[LogReg] Starting hyperparameter search over {len(all_param_combos)} combinations...")

    start_time = time.time()

    for i, params in enumerate(all_param_combos, start=1):
        if verbose:
            print(f"\n[LogReg] Combination {i}/{len(all_param_combos)}: {params}")

        # Build LR with current params
        lr = LogisticRegression(
            **params,
            random_state=random_state,
            n_jobs=-1,
            max_iter=1000,
        )

        try:
            lr.fit(X_train, y_train)
        except Exception as e:  # noqa
            if verbose:
                print(f"[LogReg] Failed with parameters {params} due to: {e}")
            continue

        # Evaluate on validation
        y_val_pred = lr.predict(X_val)
        f1_val = f1_score(y_val, y_val_pred, average="weighted")

        if verbose:
            print(f"[LogReg] Validation weighted F1: {f1_val:.4f}")

        # Update best if improved
        if f1_val > best_f1:
            best_f1 = f1_val
            best_model = lr
            best_params = params

    total_time = time.time() - start_time

    if best_model is None:
        raise RuntimeError("No valid Logistic Regression model was found during tuning.")

    if verbose:
        print("\n[LogReg] Hyperparameter search completed.")
        print(f"[LogReg] Best params: {best_params}")
        print(f"[LogReg] Best validation weighted F1: {best_f1:.4f}")
        print(f"[LogReg] Total tuning time: {total_time:.2f} seconds")

    return best_model, best_params, float(best_f1)


# -------------------------------------------------------------------
# 2. Convenience wrappers: text-only vs text+extra
# -------------------------------------------------------------------

def train_logreg_text_only(
    X_train_text,
    y_train: Sequence[int],
    X_val_text,
    y_val: Sequence[int],
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[LogisticRegression, Dict[str, Any], float]:
    """
    Wrapper for text-only Logistic Regression.
    """
    return train_logreg(
        X_train_text=X_train_text,
        y_train=y_train,
        X_val_text=X_val_text,
        y_val=y_val,
        X_train_extra=None,
        X_val_extra=None,
        param_grid=param_grid,
        random_state=random_state,
        verbose=verbose,
    )


def train_logreg_text_extra(
    X_train_text,
    X_train_extra,
    y_train: Sequence[int],
    X_val_text,
    X_val_extra,
    y_val: Sequence[int],
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[LogisticRegression, Dict[str, Any], float]:
    """
    Wrapper for Logistic Regression with extra numeric features.
    """
    return train_logreg(
        X_train_text=X_train_text,
        y_train=y_train,
        X_val_text=X_val_text,
        y_val=y_val,
        X_train_extra=X_train_extra,
        X_val_extra=X_val_extra,
        param_grid=param_grid,
        random_state=random_state,
        verbose=verbose,
    )


# -------------------------------------------------------------------
# 3. Prediction helper (for evaluation later)
# -------------------------------------------------------------------

def predict_logreg(
    model: LogisticRegression,
    X_test_text,
    X_test_extra=None,
):
    """
    Predict labels & probabilities for test data, handling text-only or text+extra.

    Returns
    -------
    y_pred : 1D array of predicted labels
    y_proba : 2D array [n_samples, n_classes] of predicted probabilities
    """
    X_test = _build_augmented_matrix(X_test_text, X_test_extra)
    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)
    else:
        y_proba = None

    return y_pred, y_proba