# -*- coding: utf-8 -*-
"""data_prep.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MBWDfxy46GCzlsVOEqRRgVNC0IHT-ePX
"""

# data_prep.py
from __future__ import annotations

import re
from typing import Tuple

import numpy as np
import pandas as pd
from sklearn.model_selection import GroupShuffleSplit
from sklearn.preprocessing import LabelEncoder


# --------- Text cleaning --------- #

def clean_text_master(text: str) -> str:
    """
    Simple, robust text cleaning:
    - lowercases
    - replaces URLs, @handles, and hashtags with placeholders
    - strips punctuation
    - collapses whitespace
    """
    if pd.isna(text):
        return ""

    text = str(text).lower()
    text = re.sub(r"http\S+", "<URL>", text)
    text = re.sub(r"@\w+", "<USER>", text)
    text = re.sub(r"#\w+", "<HASHTAG>", text)
    text = re.sub(r"[^\w\s]", "", text)   # <-- keep letters/digits/underscore + whitespace
    text = re.sub(r"\s+", " ", text)
    return text.strip()


# --------- Extra features from ai_p_* columns --------- #

def add_ai_entropy_and_confidence(
    df_raw: pd.DataFrame,
    prob_prefix: str = "ai_p_",
) -> pd.DataFrame:
    """
    From per-class probability columns (e.g. ai_p_0, ai_p_1, ...),
    compute and append:
      - ai_entropy: Shannon entropy
      - ai_entropy_norm: entropy normalized by log(K)
      - ai_max_prob: max class probability
      - ai_max_prob_norm: confidence normalized so 0 ~ uniform, 1 ~ confident
    If no columns start with prob_prefix, returns df unchanged.
    """
    df = df_raw.copy()

    prob_cols = [c for c in df.columns if c.startswith(prob_prefix)]
    if not prob_cols:
        return df  # nothing to do

    eps = 1e-12
    p = df[prob_cols].to_numpy(dtype=float)
    p = np.clip(p, eps, 1.0)

    # Renormalize rows defensively
    row_sums = p.sum(axis=1, keepdims=True)
    p = p / np.where(row_sums == 0.0, 1.0, row_sums)

    K = p.shape[1]

    # Entropy
    entropy_raw = -(p * np.log(p)).sum(axis=1)
    entropy_norm = entropy_raw / np.log(K)
    df["ai_entropy"] = entropy_raw
    df["ai_entropy_norm"] = entropy_norm

    # Max prob + normalized max prob
    max_prob_raw = p.max(axis=1)
    df["ai_max_prob"] = max_prob_raw

    uniform_prob = 1.0 / K
    denom = (1.0 - uniform_prob)
    max_prob_norm = (max_prob_raw - uniform_prob) / denom
    max_prob_norm = np.clip(max_prob_norm, 0.0, 1.0)
    df["ai_max_prob_norm"] = max_prob_norm

    return df


# --------- Build clean dataset --------- #

def build_clean_dataset(
    df_raw: pd.DataFrame,
    text_col: str,
    label_col: str,
    label_col_encoded: str = "label_id",
    prob_prefix: str = "ai_p_",
    use_ai_features: bool = True,
) -> Tuple[pd.DataFrame, LabelEncoder]:
    df = df_raw.copy()

    # Text cleaning
    df[text_col] = df[text_col].apply(clean_text_master)

    # Label encoding
    le = LabelEncoder()
    df[label_col_encoded] = le.fit_transform(df[label_col])

    # Optional ensemble-based features
    if use_ai_features:
        df = add_ai_entropy_and_confidence(df, prob_prefix=prob_prefix)

    return df, le


# --------- Group-aware train/val/test split --------- #

def split_train_val_test_grouped(
    df_clean: pd.DataFrame,
    group_col: str,
    label_col_encoded: str,
    test_size: float = 0.20,
    val_size_of_train: float = 0.25,
    random_state: int = 2025,
    split_col: str = "split",
) -> Tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    """
    Group-aware split into train / val / test (same logic as notebook):

      1) GroupShuffleSplit: train+val vs test (test_size of full data)
      2) GroupShuffleSplit on the train+val subset: train vs val
         (val_size_of_train fraction of the train+val subset)

    Returns:
      df_train, df_val, df_test, df_all_with_split
    """
    df = df_clean.copy().reset_index(drop=True)

    groups = df[group_col]
    y = df[label_col_encoded]

    # 1) Train+val vs test
    gss_test = GroupShuffleSplit(
        n_splits=1,
        test_size=test_size,
        random_state=random_state,
    )
    train_idx, test_idx = next(gss_test.split(df, y, groups=groups))

    split = np.array(["train"] * len(df), dtype=object)
    split[test_idx] = "test"
    df[split_col] = split

    # 2) Train vs val inside non-test portion
    train_mask = df[split_col] == "train"
    train_pos_indices = np.where(train_mask)[0]
    df_train_only = df.loc[train_mask].copy().reset_index(drop=True)

    groups_train = df_train_only[group_col]
    y_train = df_train_only[label_col_encoded]

    gss_val = GroupShuffleSplit(
        n_splits=1,
        test_size=val_size_of_train,   # e.g. 0.25 of 0.8 => 0.2 overall
        random_state=random_state,
    )
    train_idx2, val_idx = next(gss_val.split(df_train_only, y_train, groups=groups_train))

    # Map back to global indices
    train2_global = train_pos_indices[train_idx2]
    val_global = train_pos_indices[val_idx]

    split[:] = "train"
    split[val_global] = "val"
    split[test_idx] = "test"
    df[split_col] = split

    # Optional sanity check: each group appears in only one split
    group_split_counts = df.groupby(group_col)[split_col].nunique()
    n_leaky_groups = (group_split_counts > 1).sum()
    assert n_leaky_groups == 0, "Some groups leak across splits!"

    df_train = df[df[split_col] == "train"].copy()
    df_val   = df[df[split_col] == "val"].copy()
    df_test  = df[df[split_col] == "test"].copy()

    return df_train, df_val, df_test, df