# -*- coding: utf-8 -*-
"""ml_rf.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1we6w7bCYtmBHkmwBClY5pm1L4NjOmBV9
"""

from __future__ import annotations

import itertools
import time
from typing import Any, Dict, Optional, Sequence, Tuple

import numpy as np
from scipy.sparse import hstack, csr_matrix, issparse
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import f1_score


# -------------------------------------------------------------------
# 0. Internal helper: combine text + extra features
# -------------------------------------------------------------------

def _build_augmented_matrix(X_text, X_extra):
    """
    Combine text features (typically TF-IDF) with extra numeric features.
    If X_extra is None, returns X_text as-is.

    Parameters
    ----------
    X_text : sparse matrix (e.g. CSR from TF-IDF)
    X_extra : dense array or sparse matrix, or None

    Returns
    -------
    X_aug : combined feature matrix
    """
    if X_extra is None:
        return X_text

    if not issparse(X_text):
        raise ValueError("X_text should be a sparse matrix (e.g., TF-IDF).")

    if X_extra is not None and not issparse(X_extra):
        X_extra = csr_matrix(X_extra)

    return hstack([X_text, X_extra])


# -------------------------------------------------------------------
# 1. Core trainer (feature-agnostic)
# -------------------------------------------------------------------

def train_rf(
    X_train_text,
    y_train: Sequence[int],
    X_val_text,
    y_val: Sequence[int],
    X_train_extra=None,
    X_val_extra=None,
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[RandomForestClassifier, Dict[str, Any], float]:
    """
    Core Random Forest training with manual grid search.

    Works with:
      - text-only:   pass X_*_extra=None
      - text+extra:  pass extra feature arrays/matrices

    Uses weighted F1 on the validation set to select the best model.

    Parameters
    ----------
    X_train_text, X_val_text : sparse matrices (TF-IDF or similar)
    X_train_extra, X_val_extra : np.ndarray or sparse matrices (or None)
    y_train, y_val : label arrays
    param_grid : dict of hyperparameters -> list of values
    random_state : RNG seed for RF
    verbose : print progress

    Returns
    -------
    best_model : fitted RandomForestClassifier
    best_params : dict of best hyperparameters
    best_f1 : best validation F1 (weighted)
    """
    if param_grid is None:
        param_grid = {
            "n_estimators": [200, 500],
            "max_depth": [None, 20, 50],
            "min_samples_split": [2, 5],
            "min_samples_leaf": [1, 2],
            "max_features": ["sqrt", "log2"],
            "class_weight": ["balanced", None],
        }

    # Combine features
    X_train = _build_augmented_matrix(X_train_text, X_train_extra)
    X_val = _build_augmented_matrix(X_val_text, X_val_extra)

    y_train = np.asarray(y_train)
    y_val = np.asarray(y_val)

    keys = list(param_grid.keys())
    values = [param_grid[k] for k in keys]
    all_param_combos = [dict(zip(keys, v)) for v in itertools.product(*values)]

    best_f1 = -1.0
    best_model: Optional[RandomForestClassifier] = None
    best_params: Dict[str, Any] = {}

    if verbose:
        print(f"\n[RF] Starting hyperparameter search over {len(all_param_combos)} combinations...")

    start_time = time.time()

    for i, params in enumerate(all_param_combos, start=1):
        if verbose:
            print(f"\n[RF] Combination {i}/{len(all_param_combos)}: {params}")

        rf = RandomForestClassifier(
            **params,
            random_state=random_state,
            n_jobs=-1,
        )

        try:
            rf.fit(X_train, y_train)
        except Exception as e:  # noqa
            if verbose:
                print(f"[RF] Failed with parameters {params} due to: {e}")
            continue

        y_val_pred = rf.predict(X_val)
        f1_val = f1_score(y_val, y_val_pred, average="weighted")

        if verbose:
            print(f"[RF] Validation weighted F1: {f1_val:.4f}")

        if f1_val > best_f1:
            best_f1 = f1_val
            best_model = rf
            best_params = params

    total_time = time.time() - start_time

    if best_model is None:
        raise RuntimeError("No valid RandomForest model was found during tuning.")

    if verbose:
        print("\n[RF] Hyperparameter search completed.")
        print(f"[RF] Best params: {best_params}")
        print(f"[RF] Best validation weighted F1: {best_f1:.4f}")
        print(f"[RF] Total tuning time: {total_time:.2f} seconds")

    return best_model, best_params, float(best_f1)


# -------------------------------------------------------------------
# 2. Convenience wrappers: text-only vs text+extra
# -------------------------------------------------------------------

def train_rf_text_only(
    X_train_text,
    y_train: Sequence[int],
    X_val_text,
    y_val: Sequence[int],
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[RandomForestClassifier, Dict[str, Any], float]:
    """
    Wrapper for Random Forest with text-only features.
    """
    return train_rf(
        X_train_text=X_train_text,
        y_train=y_train,
        X_val_text=X_val_text,
        y_val=y_val,
        X_train_extra=None,
        X_val_extra=None,
        param_grid=param_grid,
        random_state=random_state,
        verbose=verbose,
    )


def train_rf_text_extra(
    X_train_text,
    X_train_extra,
    y_train: Sequence[int],
    X_val_text,
    X_val_extra,
    y_val: Sequence[int],
    param_grid: Optional[Dict[str, Sequence[Any]]] = None,
    random_state: int = 42,
    verbose: bool = True,
) -> Tuple[RandomForestClassifier, Dict[str, Any], float]:
    """
    Wrapper for Random Forest with text + extra numeric features.
    """
    return train_rf(
        X_train_text=X_train_text,
        y_train=y_train,
        X_val_text=X_val_text,
        y_val=y_val,
        X_train_extra=X_train_extra,
        X_val_extra=X_val_extra,
        param_grid=param_grid,
        random_state=random_state,
        verbose=verbose,
    )


# -------------------------------------------------------------------
# 3. Prediction helper
# -------------------------------------------------------------------

def predict_rf(
    model: RandomForestClassifier,
    X_test_text,
    X_test_extra=None,
):
    """
    Predict labels & probabilities for test data, handling text-only or text+extra.

    Returns
    -------
    y_pred : 1D array of predicted labels
    y_proba : 2D array [n_samples, n_classes] of predicted probabilities
    """
    X_test = _build_augmented_matrix(X_test_text, X_test_extra)
    y_pred = model.predict(X_test)

    if hasattr(model, "predict_proba"):
        y_proba = model.predict_proba(X_test)
    else:
        y_proba = None

    return y_pred, y_proba